export default [
    {
        id:1,
        postedOn:'2024-02-12',
        title: 'iOS Developer',
        company: 'Apple',
        type:"Full time",
        experience:"Mid Level",
        location:"Remote",
        skills:["UiKit","Core Data","SwiftUI"],
        job_link: "https://www.apple.com/careers/us/",
    },
    {
        id:2,
        postedOn:'2024-01-28',
        title: 'Frontend Developer',
        company: 'Amazon',
        type:"Full time",
        experience:"Fresher",
        location:"In-Office",
        skills:["Nextjs","Tailwind Css","javaScript"],
        job_link: "https://amazon.jobs/en",
    },
    {
        id:3,
        postedOn:'2023-12-29',
        title: 'Android Developer',
        company: 'Facebook',
        type:"Part time",
        experience:"Senior Level",
        location:"Remote",
        skills:["Model view viewmodel","Kotlin"],
        job_link: "https://www.metacareers.com/areas-of-work/Facebook%20App/?p[divisions][0]=Facebook&divisions[0]=Facebook#openpositions",
    },
    {
        id:4,
        postedOn:'2024-01-29',
        title: 'Developer Advocate',
        company: 'Netflix',
        type:"Contract",
        experience:"Junior Level",
        location:"Hybrid",
        skills:["web3","Community","Content Creation"],
        job_link: "https://jobs.netflix.com/",
        companyUrl:"https://www.facebook.com/",
    },
]